export { Room } from "./room";
export { Agent } from "./agent";
export { Item } from "./item";
export { Info, Information, IPredicate } from "./information";
export { Conversation } from "./conversation";
export { Trade } from "./trade";
export { Quest } from "./quest";
export { Faction } from "./faction";
export { Recipe } from "./recipe";
export { aNames as Predicates } from "./information";
export * from "./Imodel";
